import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [tomorrowMaxTemp, setTomorrowMaxTemp] = useState(null);
  const [location, setLocation] = useState(null);

  useEffect(() => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          const latitude = position.coords.latitude;
          const longitude = position.coords.longitude;
          setLocation(`${latitude},${longitude}`);
        },
        (error) => {
          console.log(error);
        }
      );
    }



    axios
      .get(
        `https://api.tomorrow.io/v4/timelines?location=${location}&fields=temperatureMax&timesteps=1d&units=metric&apikey=${process.env.NEXT_API_KEY}`
      )
      .then((response) => {
        const tomorrowMaxTemp =
          response.data.data.timelines[0].intervals[1].values.temperatureMax;
        setTomorrowMaxTemp(tomorrowMaxTemp);
      })
      .catch((error) => {
        console.log(error);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        What is the weather tomorrow?
        <div>{Math.ceil(tomorrowMaxTemp)}</div>
      </main>
    </>
  );
}
